variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - check
  - build

prettier:
  stage: check
  image: node:12
  before_script:
    - node --version
    - npm install
  script:
    - npm run lint

jest:
  stage: check
  image: node:12
  before_script:
    - node --version
    - npm install
  script:
    - npm run test

nix-dry:
  stage: check
  image: nixos/nix:2.3
  # image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner
  before_script:
    - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    - nix-channel --update
    - nix-env -i git
    - nix-env -i docker
    # - docker login registry.gitlab.com -u robert-cronin -p $RC_CI_BUILD_TOKEN
  script:
    - nix-build -v -v --dry-run ./release.nix --attr application
    - nix-build -v -v --dry-run ./release.nix --attr docker

nix:
  stage: build
  image: nixos/nix:2.3
  # image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner
  before_script:
    - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    - nix-channel --update
    - nix-env -i git
    - nix-env -i docker
    # - docker login registry.gitlab.com -u robert-cronin -p $RC_CI_BUILD_TOKEN
  script:
    - nix-build ./release.nix --attr application
    - nix-build ./release.nix --attr docker
